In [1]:
import numpy as np
import pandas as pd
df = pd.read_csv("kenan.csv", index_col="集数")
df

          片名  上映时间  最终票房（亿日元）
集数
1      引爆摩天楼  1997       11.0
2     第十四号猎物  1998       18.5
3    世纪末的魔术师  1999       26.0
4    瞳孔中的暗杀者  2000       25.0
5   往天国的倒数计时  2001       29.0
6     贝克街的亡灵  2002       34.0
7     迷宫的十字路  2003       32.0
8     银翼的奇术师  2004       28.0
9    水平线上的阴谋  2005       21.5
10   侦探们的镇魂歌  2006       30.3
11      绀碧之棺  2007       25.3
12     战栗的乐谱  2008       24.2
13    漆黑的追迹者  2009       35.0
14    天空的劫难船  2010       32.0
15   沉默的15分钟  2011       31.5
16    第11位前锋  2012       32.9
17     绝海的侦探  2013       36.3
18   异次元的狙击手  2014       41.1
19    业火的向日葵  2015       44.8
20     纯黑的恶梦  2016       63.3
21     唐红的恋歌  2017       68.9
22     零的执行人  2018       91.0

In [2]:
# 维度查看
df.shape

(22, 3)

In [3]:
df.describe()

              上映时间  最终票房（亿日元）
count    22.000000  22.000000
mean   2007.500000  35.527273
std       6.493587  17.968098
min    1997.000000  11.000000
25%    2002.250000  25.475000
50%    2007.500000  31.750000
75%    2012.750000  35.975000
max    2018.000000  91.000000

In [ ]:
# 数据表基本信息（维度、列名称、数据格式、所占空间等）
df.info()

In [ ]:
# 查看所有行的行索引名
row_indx_name = df.index.values #得到一个列表
row_indx_name

In [ ]:
# 查看所有列的列索引名
df.columns.values

In [ ]:
# 定位表格中的指定元素
# 要在pandas.DataFrame中的任何位置检索或更改数据，可以使用at，iat，loc，iloc。
# print(df.at['行标签名', '列标签名'])
# print(df.iat['行索引号', '列索引号'])
 
# print(df.loc['行标签名', '列标签名'])
# print(df.iloc[行索引数字, 列索引数字])
 
# print(df.loc['行标签名1':'行标签名2', '列标签名1': '列标签名2'])
# print(df.iloc[行索引数字1:行索引数字2, 列索引数字1:列索引数字2])

print(df.iat[1, 1])


# print(df.loc['行标签名', '列标签名'])
print(df.iloc[1, 1])
 
# print(df.loc['行标签名1':'行标签名2', '列标签名1': '列标签名2'])
print(df.iloc[1:4, 1:4])

In [ ]:
df = df.rename(columns={'最终票房（亿日元）': '票房'}) 
df

In [ ]:
# 更改数据格式
df["上映时间"].astype('int')

In [ ]:
# 每一列数据的格式
df.dtypes

In [ ]:
# 查看某一列的所有值 
df["片名"].values # 获取某一列的所有数值 
# 说明:需要先用对应列的列名称“姓名”获取对应列对象，然后用.values将对象转变为列表

In [ ]:
# 查看某一行的数据
df.iloc[3].values #获取第3行数据

In [ ]:
# 查看数据表的值
df.values

In [ ]:
# 查看前5行数据、后5行数据
df.head() #默认前5行数据

In [ ]:
df.tail()    #默认后5行数据

In [ ]:
# 选择满足特定条件的行
#选取 属性“a” 中 大于1的行：
df[df["票房"]>30.0]

In [ ]:
# 删除先出现的重复值
df['片名'].drop_duplicates(keep='last')

In [ ]:
# 删除后出现的重复值
df['片名'].drop_duplicates()

In [ ]:
# 数据替换
df['片名'].replace('绀碧之棺', '绀碧之*')

In [ ]:
import pandas as pd

df = pd.read_csv('scores.csv')

# #显示所有列
# pd.set_option('display.max_columns', None)

# #显示所有行
# pd.set_option('display.max_rows', None)

# #设置value的显示长度为100，默认为50
# pd.set_option('max_colwidth',100) 
df.info()
df["评分人数"].astype("float")
df["评分"].astype("float")
df.isnull().any()
df

In [ ]:
# df.groupby("评分网站")["评分"].apply(lambda x: x.fillna(x.mean()))
df["评分"] = df["评分"].fillna(df.groupby("评分网站")["评分"].transform("mean"))
df["评分人数"] = df["评分人数"].fillna(df.groupby("评分网站")["评分人数"].transform("min"))
df

In [ ]:
import pandas as pd

# 创建一个Series对象，指定名称为'A'，值分别为1, 2, 3, 4
# 默认索引为0, 1, 2, 3
series = pd.Series([1, 2, 3, 4], name='A')

# 显示Series对象
print(series)

# 如果你想要显式地设置索引，可以这样做：
custom_index = [1, 2, 3, 4]  # 自定义索引
series_with_index = pd.Series([1, 2, 3, 4], index=custom_index, name='A')

# 显示带有自定义索引的Series对象
print(series_with_index)

In [ ]:
import pandas as pd

a = [1111, 2222, 3333]

s = pd.Series(a)

print(s)

# 获取索引
index = s.index
print(index)

# 获取值数组
values = s.values
print(values)

# 获取描述统计信息
stats = s.describe()

print(stats)

# 获取最大值和最小值的索引
max_index = s.idxmax()
min_index = s.idxmin()

print(max_index)
print(min_index)

# 其他属性和方法
print(s.dtype)   # 数据类型
print(s.shape)   # 形状
print(s.size)    # 元素个数
print(s.head())  # 前几个元素，默认是前 5 个
print(s.tail())  # 后几个元素，默认是后 5 个

In [ ]:
import pandas as pd

# 创建 DataFrame
data = {
    'Name': ['A', 'B', 'C'],
    'Age': [25, 30, 35],
    'City': ['NY', 'LA', 'CC']
}
df = pd.DataFrame(data)

# 查看前两行数据
print(df.head(2))

# 查看 DataFrame 的基本信息
print(df.info())

# 获取描述统计信息
print(df.describe())